# Generated by Django 4.2 on 2025-05-31 20:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Todo', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='todo',
            old_name='competed',
            new_name='completed',
        ),
    ]
