# Generated by Django 4.2 on 2025-05-31 21:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Todo', '0002_rename_competed_todo_completed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='task',
            field=models.CharField(max_length=10000),
        ),
    ]
